name = "shopwice-frontend"
compatibility_date = "2026-02-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".cf-pages-deploy"

[vars]
NEXT_PUBLIC_SITE_URL = "https://shopwice.com"
NEXT_PUBLIC_GRAPHQL_URL = "https://api.shopwice.com/graphql"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "shopwice-media"
